### ISSUE TITLE
Uncaught Error

### ISSUE THREAD

**Issue by pasta870** [jigsaw-4277821/PE-0.5.2-Android#1]
### Describe your bug here.

Says:

Uncaught Error:
android/FlxVirtualPad.hx (line 145)
android/FlxVirtualPad.hx (line 97)
MusicBeatState.hx (line 44)
FlashingState.hx (line 38)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)
Null Object Reference

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Neko, HashLink, or other build system

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by jigsaw-4277821** [comment]
Download again

**Comment by Fakekris** [comment]
Hey Jigsaw, How I Add Shaders And Achievments to PE 0.5.2? if you don't know, fine

**Comment by DanisLixo** [comment]
> Hey Jigsaw, How I Add Shaders And Achievments to PE 0.5.2? if you don't know, fine

you can't add shaders, nor achievements, their folder only exist with no function
